# -*- coding: utf-8 -*-
"""textTosql_peft_inference.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1JuQkVYSesz_QhODSC1lkEURoAfCsmI4V
"""

!pip install transformers

from transformers import AutoTokenizer, AutoModelForCausalLM, GenerationConfig
import torch
import sys
import sqlite3
from sql_func import populate_database, test_database
sys.path.append('/content')

from transformers import (
    AutoTokenizer,
    AutoModelForSeq2SeqLM,
    TrainingArguments,
    Trainer
)
import os
from peft import LoraConfig, PeftModel  # Import LoraConfig from peft

from google.colab import drive


populate_database()
drive.mount('/content/drive')
model_name = "Salesforce/codet5-base"
tokenizer = AutoTokenizer.from_pretrained(model_name)
base_model = AutoModelForSeq2SeqLM.from_pretrained(model_name)
model_dir = "/content/drive/MyDrive/model"
model = PeftModel.from_pretrained(base_model, model_dir)
tokenizer = AutoTokenizer.from_pretrained(model_name)

#conn = sqlite3.connect(':memory:')
conn = sqlite3.connect("file::memory:?cache=shared")
cursor = conn.cursor()
# Dump schema
cursor.execute("SELECT name, sql FROM sqlite_master WHERE type='table';")
schema = cursor.fetchall()


# Inference
prompt = schema + ":" + "translate question to SQL: Write a sql to show count of records for table t"
inputs = tokenizer(prompt, return_tensors="pt").to(model.device)
outputs = model.generate(**inputs, max_length=5000,min_new_tokens=50)
populate_database()
decoded_output = tokenizer.decode(outputs[0], skip_special_tokens=True)
print('SQL Output', decoded_output)
test_database(decoded_output)

